### ISSUE TITLE
Active? Examples?

### ISSUE THREAD

**Issue by ricopicone** [lawrennd/proceedings#10]
Is this still an active project? Are there any examples of its use for conference proceedings? Thanks!

**Comment by lawrennd** [comment]
Absolutely, it's not edited recently, and one problem is that it's forked in its deployment. 

Check

https://github.com/mlresearch/jekyll-theme

Which builds on it. That powers PMLR which is 256 volumes published.

Happy to take input on how those changes can be pulled back in and what the right structure is for easier sharing and modification across projects ... if that's what you're interested in! I've not gone through that stage of refactoring yet and am sure there are better ways of doing things!

**Comment by ricopicone** [comment]
Awesome, thanks! I'll take a closer look.
