### ISSUE TITLE
special character '&' couldnt work for tex_title in latex.

### ISSUE THREAD

**Issue by XiaoxiWei** [lawrennd/proceedings#4]
The '&' character in the tex_title result in additional 'amp' ';' letters in the BibTeX paper title generated from the website.

**Comment by lawrennd** [comment]
Thanks Xiaoxi! I've been looking at why this happens ... and it's to do with the JavaScript ... it puts it in because & is potentially a malicious character (e.g. in cgi-bin).

**Comment by XiaoxiWei** [comment]
Dear Neil,
Thanks for checking. I was thinking of the same reason.
I noticed you changed the paper tex_title back to ‘\’ ‘&’, but the ‘amp’ problem came back.


If you check https://proceedings.mlr.press/v176/wei22a.html and press the BibTeX Copy to clipboard button, the amp thing is still in the ’latex_title’. maybe using ‘\’ ‘{‘ ‘&’ ‘}’ would solve the problem once the backend malicious problem is solved.


Other-wise, if the problem is technically too difficult, I would still replacing it with ‘and’.


Thanks for the time.


Best regards,
Xiaoxi
@




---- Replied Message ----
| From | Neil ***@***.***> |
| Date | 11/21/2022 17:18 |
| To | ***@***.***> |
| Cc | Xiaoxi ***@***.***> ,
***@***.***> |
| Subject | Re: [lawrennd/proceedings] special character '&' couldnt work for tex_title in latex. (Issue #4) |

Thanks Xiaoxi! I've been looking at why this happens ... and it's to do with the JavaScript ... it puts it in because & is potentially a malicious character (e.g. in cgi-bin).

**Comment by lawrennd** [comment]
Oh ... thanks for noticing! It was part of my testing. I'll flip it back. And thanks for your patience and your work on problem diagnosis. I'll close this issue now.

**Comment by XiaoxiWei** [comment]
Many thanks!
Xiaoxi




---- Replied Message ----
| From | Neil ***@***.***> |
| Date | 11/22/2022 14:01 |
| To | ***@***.***> |
| Cc | Xiaoxi ***@***.***> ,
***@***.***> |
| Subject | Re: [lawrennd/proceedings] special character '&' couldnt work for tex_title in latex. (Issue #4) |

Oh ... thanks for noticing! It was part of my testing. I'll flip it back. And thanks for your patience and your work on problem diagnosis. I'll close this issue now.
